"""Render the final social preview, with an optional thumbnail review sheet."""

import argparse
from io import BytesIO
from pathlib import Path

import resvg_py
from PIL import Image, ImageDraw, ImageFont


ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / "assets/social-preview"


def main() -> None:
    """Regenerate the PNG artifacts with the existing image-tool dependencies."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--source", type=Path, default=ASSETS / "social-preview.svg",
        help="Editable SVG to render (defaults to the final source)",
    )
    parser.add_argument(
        "--review-output", type=Path,
        help="Optional thumbnail review sheet path; no review is generated by default",
    )
    args = parser.parse_args()
    source = args.source.resolve()
    brand_font = ASSETS / "fonts/FloriInputUI-Medium.ttf"
    if not brand_font.is_file():
        raise FileNotFoundError(f"Required font not found: {brand_font}")

    png = resvg_py.svg_to_bytes(
        svg_path=str(source),
        resources_dir=str(source.parent),
        skip_system_fonts=True,
        font_files=[str(brand_font)],
        font_family="FloriInputUI",
        sans_serif_family="FloriInputUI",
        languages=["zh-CN", "en"],
    )
    with Image.open(BytesIO(png)) as rendered:
        if rendered.size != (1280, 640):
            raise ValueError(f"Expected 1280x640 source, got {rendered.size}")
        preview = rendered.convert("RGB")
    output = BytesIO()
    preview.save(output, format="PNG", optimize=True)
    if output.tell() >= 1_000_000:
        raise ValueError("Social preview must be under 1,000,000 bytes")

    source.with_suffix(".png").write_bytes(output.getvalue())
    print(f"{source.stem}: 1280x640 PNG, {output.tell():,} bytes")

    if args.review_output is not None:
        thumbnail = preview.resize((320, 160), Image.Resampling.LANCZOS)
        review = Image.new("RGB", (720, 224), "#d0d7de")
        draw = ImageDraw.Draw(review)
        font = ImageFont.truetype(str(brand_font), 12)
        for left, background, label, color in (
            (12, "#ffffff", "LIGHT SURROUND", "#57606a"),
            (366, "#0d1117", "DARK SURROUND", "#8c959f"),
        ):
            draw.rounded_rectangle((left, 12, left + 342, 212), radius=12, fill=background)
            draw.text((left + 10, 17), label, font=font, fill=color)
            review.paste(thumbnail, (left + 10, 42))
        review_output = args.review_output.resolve()
        review_output.parent.mkdir(parents=True, exist_ok=True)
        review.save(review_output, optimize=True)
        print(f"Review sheet: {review_output}")


if __name__ == "__main__":
    main()
